registration/urls.py
from django.contrib import admin
from django.urls import path
from registration import views
from django.conf import settings
from django.conf.urls.static import static
from .views import add_record, success, mycollection 
from . import views
import pymongo
from django.conf.urls.static import static


# ,delete_record

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('admin/', admin.site.urls),
    path('home/', views.HomePage, name='home'),
    path('Record_Management', views.Record_Management, name='Record_Management'),
    path('Crud', views.Crud, name='Crud'),
    path('signup', views.SignupPage, name='signup'),
    path('login', views.LoginPage, name='login'),
    path('logout', views.LogoutPage, name='logout'),
    path('add_record', views.add_record, name='add_record'),
    path('delete_record', views.delete_record, name='delete_record'),
    path('success/', views.success, name='success'),
    path('show_records', views.show_records, name='show_records'),
    # path('open-web-camera/', views.open_web_camera, name='open_web_camera'),
    path('recognize_face', views.recognize_face, name='recognize_face'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
import uuid

class MyCollection(models.Model):
    CriminalName = models.CharField(max_length=100)
    Age = models.IntegerField()
    Criminality = models.CharField(max_length=100, default='')
    CriminalPic = models.FileField(upload_to='uploads/')
    record_id = models.UUIDField(default=uuid.uuid4, editable=False)
    
    def __str__(self):
        return self.CriminalName
    

app1/forms.py
from django import forms
from .models import MyCollection



class MyCollectionForm(forms.ModelForm):
    class Meta:
        model = MyCollection
        fields = ['CriminalName','Age', 'Criminality', 'CriminalPic']



class DeleteRecordForm(forms.Form):
    record_id = forms.ModelChoiceField(queryset=MyCollection.objects.all(), empty_label=None, widget=forms.Select(attrs={'class': 'form-control'}))

templates/Crud.html
{% load static %}
<!doctype html>
<html lang="en">
  
  <head>
    <style>


      body {
        user-select: none;
        -webkit-user-select: none;
        background-image: url('{% static "images/bg2.jpg" %}');
        background-size: cover;
        background-position: cover;
        background-color: #6495ED;
      }
    

.button-49,
.button-49:after {
  width: 190px;
  height: 76px;
  line-height: 78px;
  font-size: 20px;
  font-family: 'Bebas Neue', sans-serif;
  background: linear-gradient(45deg, transparent 5%, #4169E1 5%);
  border: 0;
  color: #fff;
  letter-spacing: 1x;
  box-shadow: 6px 0px 0px #00E6F6;
  outline: transparent;
  position: relative;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

.button-49:after {
  --slice-0: inset(50% 50% 50% 50%);
  --slice-1: inset(80% -6px 0 0);
  --slice-2: inset(50% -6px 30% 0);
  --slice-3: inset(10% -6px 85% 0);
  --slice-4: inset(40% -6px 43% 0);
  --slice-5: inset(80% -6px 5% 0);
  
  content: 'ALTERNATE TEXT';
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: linear-gradient(45deg, transparent 3%, #00E6F6 3%, #00E6F6 5%, #FF013C 5%);
  text-shadow: -3px -3px 0px #F8F005, 3px 3px 0px #00E6F6;
  clip-path: var(--slice-0);
}

.button-49:hover:after {
  animation: 1s glitch;
  animation-timing-function: steps(2, end);
}

@keyframes glitch {
  0% {
    clip-path: var(--slice-1);
    transform: translate(-20px, -10px);
  }
  10% {
    clip-path: var(--slice-3);
    transform: translate(10px, 10px);
  }
  20% {
    clip-path: var(--slice-1);
    transform: translate(-10px, 10px);
  }
  30% {
    clip-path: var(--slice-3);
    transform: translate(0px, 5px);
  }
  40% {
    clip-path: var(--slice-2);
    transform: translate(-5px, 0px);
  }
  50% {
    clip-path: var(--slice-3);
    transform: translate(5px, 0px);
  }
  60% {
    clip-path: var(--slice-4);
    transform: translate(5px, 10px);
  }
  70% {
    clip-path: var(--slice-2);
    transform: translate(-10px, 10px);
  }
  80% {
    clip-path: var(--slice-5);
    transform: translate(20px, -10px);
  }
  90% {
    clip-path: var(--slice-1);
    transform: translate(-10px, 0px);
  }
  100% {
    clip-path: var(--slice-1);
    transform: translate(0);
  }
}

@media (min-width: 768px) {
  .button-49,
  .button-49:after {
    width: 200px;
    height: 86px;
    line-height: 88px;
  }
}

.BtnMove{
  position: relative;
  left:88%;
}


   


     </style>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Scan - O - Spectacles</title>
  </head>
  
  <body>
    <div class="container-fluid">
      <h1 class="text-center mt-5 mb-5" style="color:white; font-size: 4vw;font-family: Courier New, monospace;font-weight: bold;">Scan - O - Records</h1>
      <div class="row justify-content-between">
  
      </div>
      <div style="color:white;" class="table-responsive" style="display: inline-table;">
        <h2 style="font-size: 3vw;">Criminal Records</h2>
        {% if records %}
        <table style="backdrop-filter: blur(10px);" class="table table-hover table-bordered   w-75  ">
          <thead class="" style="color:white;">
            <tr>
              <th style="font-size: 2vw;">Criminal Name</th>
              <th style="font-size: 2vw;">Criminality</th>
              <th style="font-size: 2vw;">Age</th>
              <th style="font-size: 2vw;">Picture</th>
            </tr>
          </thead>
          <tbody>
            {% for record in records %}
            <tr style="color:white;font-size: 1.2vw;font-weight: bolder;">
              <td>{{ record.CriminalName }}</td>
              <td>{{ record.Criminality }}</td>
              <td>{{ record.Age }}</td>
              <td><img src="{{ record.CriminalPic.url }}" alt="{{ record.CriminalName }}" style="max-width: 100px;"></td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="3">No records found.</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>No records found.</p>
        {% endif %}
      </div>
      
      <div class="mb-">
        <a  href="{% url 'show_records' %}"  type = "button"
        class="btn btn-lg BtnMove   " style="display: inline-block;position: absolute;Bottom:65%;background-image: linear-gradient(to right, #8B939A , #5B6467);" >Show Record</a>
        </div>
        <div class=" mb-">
          <a href="{% url 'add_record' %}" type = "button"
           class="btn btn-lg  BtnMove " style="display: inline-block;position: absolute;Bottom:55%;background-image: linear-gradient(to right, #8B939A , #5B6467);">Add Record</a>
        </div>
        <div class="mb-">
          <a href="{% url 'delete_record' %}"  type = "button"
           class="btn btn-lg  BtnMove" style="display: inline-block;position: absolute;Bottom:45%;background-image: linear-gradient(to right, #8B939A , #5B6467);">Delete Record</a>
        </div>
        <div class="mb-">
          <a href="{% url 'logout' %}"  type = "button"
          class="btn btn-lg BtnMove " style="display: inline-block;position: absolute;Bottom:35%;background-image: linear-gradient(to right, #8B939A , #5B6467);">Logout</a>
        </div>
        <div class="mb-">
          <a href="{% url 'Record_Management' %}" type = "button"
           class="btn btn-lg   BtnMove " style="display: inline-block;position: absolute;Bottom:25%;background-image: linear-gradient(to right, #8B939A , #5B6467);">Back</a>
        </div>
      </div>
    </div>
    </div>
    </div>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
  </body>
</html>

templates/Record_Management.html
  {% load static %}
  <!doctype html>
  <html lang="en">
    
    <head>
      <style>

        body {
          user-select: none;
          -webkit-user-select: none;
          background-image: url('{% static "images/bg.jpg" %}');
          background-size: cover;
          background-position: cover;
          background-color: #6495ED;
        }

  .button-49,
  .button-49:after {
    width: 190px;
    height: 76px;
    line-height: 78px;
    font-size: 20px;
    font-family: 'Bebas Neue', sans-serif;
    background: linear-gradient(45deg, transparent 5%, #4169E1 5%);
    border: 0;
    color: #fff;
    letter-spacing: 1x;
    outline: transparent;
    position: relative;
    user-select: none;
    -webkit-user-select: none;
    touch-action: manipulation;
  }

  .button-49:after {
    --slice-0: inset(50% 50% 50% 50%);
    --slice-1: inset(80% -6px 0 0);
    --slice-2: inset(50% -6px 30% 0);
    --slice-3: inset(10% -6px 85% 0);
    --slice-4: inset(40% -6px 43% 0);
    --slice-5: inset(80% -6px 5% 0);
    
    content: 'ALTERNATE TEXT';
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(45deg, transparent 3%, #00E6F6 3%, #00E6F6 5%, #FF013C 5%);
    text-shadow: -3px -3px 0px #F8F005, 3px 3px 0px #00E6F6;
    clip-path: var(--slice-0);
  }

  .button-49:hover:after {
    animation: 1s glitch;
    animation-timing-function: steps(2, end);
  }

  @keyframes glitch {
    0% {
      clip-path: var(--slice-1);
      transform: translate(-20px, -10px);
    }
    10% {
      clip-path: var(--slice-3);
      transform: translate(10px, 10px);
    }
    20% {
      clip-path: var(--slice-1);
      transform: translate(-10px, 10px);
    }
    30% {
      clip-path: var(--slice-3);
      transform: translate(0px, 5px);
    }
    40% {
      clip-path: var(--slice-2);
      transform: translate(-5px, 0px);
    }
    50% {
      clip-path: var(--slice-3);
      transform: translate(5px, 0px);
    }
    60% {
      clip-path: var(--slice-4);
      transform: translate(5px, 10px);
    }
    70% {
      clip-path: var(--slice-2);
      transform: translate(-10px, 10px);
    }
    80% {
      clip-path: var(--slice-5);
      transform: translate(20px, -10px);
    }
    90% {
      clip-path: var(--slice-1);
      transform: translate(-10px, 0px);
    }
    100% {
      clip-path: var(--slice-1);
      transform: translate(0);
    }
  }

  @media (min-width: 768px) {
    .button-49,
    .button-49:after {
      width: 200px;
      height: 86px;
      line-height: 88px;
    }
  }
      </style>


      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <title>Scan - O - Spectacles</title>
    </head>
    <body>
      <div >
      {% comment %} <h1 style='margin-top:70px;text-align:center; font-size:4vw;'>Scan - O - Spectacles Screen 2</h1> {% endcomment %}
      <div class='form' style="text-align: center;margin-left:140px;">
        <button class='button-49' style="display: block; margin: auto; margin-top:40px;background-image: linear-gradient(to right, #8B939A , #5B6467);" onclick="openWebCamera()">Open Web Camera</button>

        <script>
          function openWebCamera() {
            // Add the code here to execute the recognize_face or findEncodings functions
            // For example:
            // Call the recognize_face function using AJAX
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '/recognize_face', true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    console.log('Facial recognition completed.');
                }
            };
            xhr.send();
          }
        </script>

        <a style="display: block; margin: auto; margin-top:30px;background-image: linear-gradient(to right, #8B939A , #5B6467);" href="{% url 'Crud' %}"
         class="button-49 text-decoration-none text-white">Record Management</a>


          <a style="display: block; margin: auto; margin-top:30px;background-image: linear-gradient(to right, #8B939A , #5B6467);" href="{% url 'logout' %}" class="button-49 text-decoration-none text-white">Logout</a>
          <a style="display: block; margin: auto; margin-top:30px;background-image: linear-gradient(to right, #8B939A , #5B6467);" href="{% url 'login' %}" class="button-49 text-decoration-none text-white">Back</a>
      </div>    
      <div/>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
  </html>

templates/add_record.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Design by foolishdeveloper.com -->
    <title>Login Page</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

    <!-- bootstrap Links-->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--Stylesheet-->
    <style media="screen">
    *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body {
    user-select: none;
    -webkit-user-select: none;
    background-image: url('{% static "images/bg4.jpg" %}');
    background-size: cover;
    background-position: cover;
    background-color: #6495ED;
    }
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 640px;
    width: 500px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 15px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 30px;
    width: 100%;
    {% comment %} background-color: #ffffff; {% endcomment %}
    background-color: ;
    color: #080710;
    padding: 6px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
    height:55px;
}



    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form class="form" method="post" enctype="multipart/form-data">
        <h3 style="font-family: Courier New, monospace;font-weight: bold;color:black;">Scan - O - Records</h3>
        {% csrf_token %} 

        <input type="hidden" id="id_record_id" name="record_id" value="{{ record_id }}">
        <label for="id_CriminalName">Criminal Name</label>
        <input type="text" placeholder="Enter Criminal Name" id="id_CriminalName" name="CriminalName">

        <label for="id_Criminality">Criminality</label>
        <input type="text" placeholder="Enter Criminality" id="id_Criminality" name="Criminality">

        <label for="id_Age">Criminal Age</label>
        <input type="number" placeholder="Criminal Age" id="id_Age" name="Age">

        <label for="id_pic">Add Picture</label>
        <input class="form-control" name="CriminalPic" placeholder="Criminal Picture" type="file">


        {% comment %} <a style="display: block; margin: auto; margin-top:30px;
        background-image: linear-gradient(to right, #8B939A , #5B6467);" href="{% url 'Crud' %}"
        class="button-49 text-decoration-none text-white">Record Management</a> {% endcomment %}



        <button style="margin-top:20px;background-image: linear-gradient(to right, #8B939A , #5B6467);"
            type="submit">Add Record</button>
        <button  type="submit" >
            <a style="color:black; margin-bottom:5px;background-image: linear-gradient(to right, #8B939A , #5B6467);" 
                class="btn btn-block btn-lg text-decoration-none"
                href="{% url 'Crud' %}">Back</a></button>

    
    </form>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    {% endif %}
</body>
</html>

templates/delete_record.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Design by foolishdeveloper.com -->
    <title>Login Page</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

    <!-- bootstrap Links-->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--Stylesheet-->
     <style media="screen">
        body {
            user-select: none;
            -webkit-user-select: none;
            background-image: url('{% static "images/bg4.jpg" %}');
            background-size: cover;
            background-position: cover;
            background-color: #6495ED;
          }


    </style> 
</head>
<body>
    <div class="container">
        <h3 style="color:white;">Delete Record Here</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="{{ form.record_id.id_for_label_tag }}">Record ID</label>

           <span style="background-color:grey;"> {{ form.record_id }} <span>

            <button  style="background-image: linear-gradient(to right, #8B939A , #5B6467);margin-top:15px;"
             type="submit" class="btn  btn-lg">Delete Record</button>

            <a style="background-image: linear-gradient(to right, #8B939A , #5B6467);margin-top:15px;color:black;"
             href="{% url 'Crud' %}" class="btn  text-decoration-none">Back</a>
        </form>

        {% if success_message %}
            <div class="alert alert-success">
                {{ success_message }}
            </div>
        {% endif %}
    </div>
</body>
</html>